### ISSUE TITLE
[Docs] Fix download link to CSV of control points in tutorial for 'Batch mode'

### ISSUE THREAD

**Issue by larsmaxfield** [olive-groves/butterfly_registrator#13]
Current link is broken in the section 'Batch mode' of the tutorial (specifically, the hyperlink '[download a copy of the control points CSV](https://olive-groves.github.io/butterfly_registrator/Registration_points-s0039V1962_Zn_MAXRF-to-s0039V1962_b_crop.csv)').

Correct link is [https://github.com/olive-groves/butterfly_registrator/releases/download/v1.0/Registration_points-s0039V1962_Zn_MAXRF-to-s0039V1962_b_crop.csv](https://github.com/olive-groves/butterfly_registrator/releases/download/v1.0/Registration_points-s0039V1962_Zn_MAXRF-to-s0039V1962_b_crop.csv)

**Comment by larsmaxfield-asml** [comment]
Fixed by [https://github.com/olive-groves/butterfly_registrator/commit/3a85c0533e74ba57a91b36107f57e0c47d1078a8](https://github.com/olive-groves/butterfly_registrator/commit/3a85c0533e74ba57a91b36107f57e0c47d1078a8).
